config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  get '/events/update_list', to: 'events#update_list'
  resources :events, except: [:index] do
    resources :likes, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:show]
  resources :likes, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :likes
  mount_uploader :pic, PhotoUploader
  validates :name, :pic, :start_time, :end_time, :capacity, :place, :link, presence: true;
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :event
  validates :rating, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :events, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  def index
    @events = Event.all
  end

  def show
    @review = Review.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(str_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(str_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
  end

  def update_list
    @query = params[:update_list][:query]
    redirect_to root_path if @query == ''
    @total = Event.all.length
    @events = Event.where("name LIKE '%#{@query}%'")
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def str_params
    params.require(:event).permit(:name, :pic, :start_time, :end_time, :capacity, :place, :link)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @user = User.first
    @event = Event.find(params[:event_id])
    @like = Like.new
    @like.user = @user
    @like.event = @event
    @like.save
    redirect_to event_path(@event)
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    redirect_to event_path(@like.event)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_evt, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(str_params)
    @review.event = @event
    if @review.save
      redirect_to event_path(@event)
    else
      render 'events/show'
    end
  end

  private

  def set_evt
    @event = Event.find(params[:event_id])
  end

  def str_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.input :pic %>
  <%= f.input :pic_cache, as: :hidden %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :capacity %>
  <%= f.input :place %>
  <%= f.input :link %>
  <%= f.submit "Submit", class: "btn btn-secondary" %>
<% end %>

app/views/events/_list.html.erb
<% @events.each do |event| %>
  <%= link_to event_path(event), class: "big-card" do%>
    <div class="mcard shadow-sm" style="background-image: url(<%= event.pic %>);">
      <div class="card-body">
        <div class="card-title">
          <h5 id="title-text"><%= event.name %></h5>
        </div>
      <div class="card-like">
        <% @user = User.first %>
        <% like = @user.likes.where("event_id=#{event.id}") %>
        <% if like.empty? %>
          <i class="far fa-heart"></i>
        <% else %>
          <i class="fas fa-heart"></i>
        <% end %>
      </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container gray-temp partial-form fontcolor">
  <h1>Edit event</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="index-banner">
  <div class="container">
    <h1 class="main-title">Enjoy the moment</h1>
    <p class="sub-title">Pick everything you like</p>
      <div class="row">
      <%= render 'list', events:@events %>
      </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container gray-temp partial-form fontcolor">
  <h1>Add new event</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="event-img">
    <%= cl_image_tag @event.pic, class: "event-img-self" %>
  </div>
  <div class="flex-con">
    <div class="event-info gray-temp fontcolor">
      <h1><%= link_to @event.name, @event.link, class: "fontcolor", target: :_blank %></h1>
      <%= link_to edit_event_path(@event) do %>
        <i class="fas fa-edit fontcolor"></i>
      <% end %>
      <% @user = User.first %>
      <% like = @user.likes.where("event_id=#{@event.id}") %>
      <% if like.empty? %>
        <%= link_to event_likes_path(@event), method: :post do %><i class="far fa-heart red-heart"></i><% end %>
      <% else %>
        <%= link_to like_path(like[0]), method: :delete do %><i class="fas fa-heart red-heart"></i><% end %>
      <% end %> <p></p>
      <p>Date: <%= @event.start_time %> - <%= @event.end_time %></p>
      <p>Capacity: <%= @event.capacity %>   Left: <%= @event.capacity - @event.users.length %></p>
      <span>Location: </span>
      <span id="address"><%= @event.place %></span>
      <div class="review"></br>
        <h2>Reviews</h2>
        <% @event.reviews.each do |review|%>
          <ul>
            <li><% review.rating.times do %>
              <i class="fas fa-grin-tongue-squint"></i>
              <% end %></br>
            <%= review.content %></li>
          </ul>
        <% end %>
        <%= render 'reviews/new_review', review: @review %>
    </div>
    </div>
    <div class="add-info gray-temp fontcolor">
      <p>Who else has interests in this event</p>
      <% @event.users.each do |user|%>
      <p><%= link_to user.name, user_path(user), class: "fontcolor" %></p>
      <% end %>
    </div>

  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/events/update_list.html.erb
<div class="index-banner">
  <div class="container">
    <h1 class="main-title">Enjoy the moment</h1>
    <p class="sub-title">You search for <%= @query %>. We found <%= @events.length %> out of <%= @total %> on out website.</p>
    <div class="row">
      <%= render 'list', events:@events %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPracticeEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' /> -->
  </head>

  <body>
    <ul class="nav flex-sm-row d-flex justify-content-between p-2 bg-light ">
      <li class="nav-item">
        <div class="dropdown">
          <i class="fas fa-bars dropbtn"></i>
          <div class="dropdown-content">
          <!-- dropdown button 1 -->
          <%= link_to "Add Event", new_event_path %>
          <!-- dropdown button 2 -->
          <%= link_to user_path(1) do %>
          <img src="<%= User.first.avatar %>" alt="" class="avatar">
          <span class="user-name"><%= User.first.name %></span>
        <% end %>
          </div>
        </div>
        <%= link_to "Happy List", root_path, class:"btn btn-light" %>
      </li>
      <li class="nav-item d-flex">
        <div class="d-inline">
          <%= form_for :update_list, url: '/events/update_list', method: :get do |f| %>
              <%= f.text_field :query, class: "text-field", placeholder: "search for events" %>
              <%= f.submit "Submit", class: "submit-button" %>
          <% end %>
        </div>
        <!-- <form class="form-inline" action="/flats/update_list">
          <input class="form-control" type="text" name="lastname">
          <input class="btn btn-outline-success ml-2 mr-2" type="submit" value="Submit">
        </form> -->
        <div>
        <%= link_to "Add Event", new_event_path, class: "btn btn-outline-secondary add-button" %>
        </div>
        <%= link_to user_path(1) ,class: "user" do %>
          <img src="<%= User.first.avatar %>" alt="" class="avatar">
          <span class="user-name"><%= User.first.name %></span>
        <% end %>
      </li>
    </ul>
    <%= yield %>
    <div class="footer">
      <div class="footer-container">
          <p class="footer-text">This website was coded with <i class="fas fa-cocktail"></i> at Le Wagon.</p>
      </div>
    </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/reviews/_new_review.html.erb
<div class="container">
  <%= simple_form_for [@event, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit "Add Review", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/show.html.erb
<div class="user-container container">
  <div class="user-content">
    <div class="user-img-con">
      <img class="user-img" src="<%= @user.avatar %>" alt="">
    </div>
    <div class="user-like">
      <div class="user-des user-font-color">
        <h1><%= @user.name  %></h1>
        <p>Description: <%= @user.description %></p>
      </div>
      <div class="user-like-list user-font-color">
        <p>This user has interests in these events:</p>
        <ul>
          <% @user.events.each do |event| %>
            <p><%= link_to event.name, event_path(event), class: "user-font-color" %></p>
          <% end %>
      </ul>
      </div>
    </div>
  </div>
</div>